name: Admin
version: 0.1
dependencies:
  Test:
    - 0.1
  Test3:
    - 0.1
conflicts:
business_objects:
  - Features
menus:
  admin:
    title: Administration
    description: Administration de l'intranet
    url: /admin
    children:
      modules:
        title: Modules
        description: Gestion des modules
        url: /features
      roles:
        title: Roles
        description: Gestion des roles
        url: /roles
      users:
        title: Users
        description: Gestion des users
        url: /users
      permissions:
        title: Permissions
        description: Gestion des permissions
        url: /permissions
configurations:
  password_policy: 
    description: Test de la description
    value: '{first_name,1}.{LAST_NAME}'
     
  conf_de_test: Ceci est un test