Osirails:
    Base:
        Test:
            activated: false
            installed: false
        Test1:
            activated: false
            installed: false
        Test2:
            activated: false
            installed: false

